## Correcting coordinates
Since some of the coordinates from Unity were not accurate, they were recalculated and will now be mapped on the final data frame.

In [1]:
import os
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### Load corrected coordinates
built on script `01_CoordinatesJasons`

In [2]:
CorrectedCoordinates = pd.read_csv('/Volumes/TwoTeras/Resources/BuildingCoordinates_short.csv')
CorrectedCoordinates.head()

,Unnamed: 0,BuildingCenterWorld.x,BuildingCenterWorld.z,Name,BuildingName,PointingTargetBuildingId,AgentID,PointingTargetCondition,Context,Agent
0,0,255.062286,-18.984482,30_SaNo,TaskBuilding_1,1,30,SaNo,False,False
1,1,255.062286,-18.984482,30_Sa,TaskBuilding_1,1,30,Sa,False,True
2,2,197.370117,234.419739,3_CmANo,TaskBuilding_2,2,3,CmANo,True,False
3,3,197.370117,234.419739,3_CmA,TaskBuilding_2,2,3,CmA,True,True
4,4,132.904114,29.115139,13_CmA,TaskBuilding_3,3,13,CmA,True,True

### Reading the participants data from the participants data reconstruction pipeline

In [3]:
CorrectedCoordinates[['AgentID', 'PointingTargetBuildingId', 'PointingTargetCondition']]

     AgentID  PointingTargetBuildingId PointingTargetCondition
0         30                         1                    SaNo
1         30                         1                      Sa
2          3                         2                   CmANo
3          3                         2                     CmA
4         13                         3                     CmA
..       ...                       ...                     ...
107        5                        57                     CmA
108       20                        58                     CmA
109       20                        58                   CmANo
110       27                        59                   CmANo
111       27                        59                     CmA

[112 rows x 3 columns]

In [4]:
PointingTask = pd.read_csv('/Volumes/TwoTeras/0_Experiment_1/Pointing_Task/Results/PointingTask_exp1.csv')
PointingTask.ImageName.astype('category')
PointingTask.ImageName.value_counts()

27_CmANo    116
41_Sa       113
54_Sa       112
16_CmA      112
21_CmANo    111
           ...
03_CmA       74
32_Sa        73
24_CmA       73
49_Sa        73
44_Sa        72
Name: ImageName, Length: 112, dtype: int64

In [5]:
PointingTask.head()

,Unnamed: 0,SubjectID,ParticipantPosition_x,ParticipantPosition_z,PointerPosition_x,PointerPosition_z,PointerDirection_x,PointerDirection_z,PointerDirection_y,TargetBuildingPosition_x,...,StartPointID.1,ID_for_StartingPosition,ImageIndexNumber,ImageName,TimeDelta,RT,TimeOut,TimeStampBegin,TimeStampEnd,Angle
0,0,365,-114.329147,-139.997375,-114.236984,-139.696228,-0.055459,0.989548,0.133112,-72.798836,...,1,1,90,46_Sa,0 days 00:00:25.825714432,25.825715,False,2021-11-18 10:22:23.050529792,2021-11-18 10:22:48.876244224,15.294643
1,1,365,-114.264938,-139.996460,-114.031693,-139.985962,0.928706,0.370576,0.013347,-7.537856,...,1,2,88,45_Sa,0 days 00:00:25.492403456,25.492404,False,2021-11-18 10:22:49.152516864,2021-11-18 10:23:14.644920320,14.686119
2,2,365,-114.299942,-139.961884,-114.061569,-139.765411,0.492234,0.865303,0.094636,132.779266,...,1,3,25,13_CmANo,0 days 00:00:19.030518016,19.030518,False,2021-11-18 10:23:14.911271936,2021-11-18 10:23:33.941789952,25.987650
3,3,365,-114.295120,-139.949188,-113.934219,-139.899109,0.925734,0.377881,0.014902,87.632721,...,1,4,80,41_Sa,0 days 00:00:17.538549248,17.538549,False,2021-11-18 10:23:34.213599744,2021-11-18 10:23:51.752148992,20.002567
4,4,365,-114.277084,-140.014740,-114.006210,-139.814026,0.587291,0.807565,0.054103,157.620819,...,1,5,71,36_SaNo,0 days 00:00:04.151518464,4.151519,False,2021-11-18 10:23:52.016517632,2021-11-18 10:23:56.168036096,9.460410

In [6]:
#Merging the updated set of coordinates from new list with final participant data set
CoordinatesIntegrated = pd.merge(PointingTask, CorrectedCoordinates,
                                 left_on= ['avatarID' , 'meaningful'],
                                 right_on=['AgentID','Context'],
                                 how='outer',
                                 suffixes= ['_drop','_keep'])
CoordinatesIntegrated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20160 entries, 0 to 20159
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0_drop                20160 non-null  int64
 1   SubjectID                      20160 non-null  int64
 2   ParticipantPosition_x          20160 non-null  float64
 3   ParticipantPosition_z          20160 non-null  float64
 4   PointerPosition_x              20160 non-null  float64
 5   PointerPosition_z              20160 non-null  float64
 6   PointerDirection_x             20160 non-null  float64
 7   PointerDirection_z             20160 non-null  float64
 8   PointerDirection_y             20160 non-null  float64
 9   TargetBuildingPosition_x       20160 non-null  float64
 10  TargetBuildingPosition_z       20160 non-null  float64
 11  DistanceToParticipant          20160 non-null  float64
 12  avatarID                       20160 non-null  int64
 13  AvatarPresence                 20160 non-null  bool
 14  AvatarPresenceCategory         20160 non-null  object
 15  meaningful                     20160 non-null  bool
 16  meaningfulBuilding             20160 non-null  object
 17  StartPointID                   20160 non-null  int64
 18  PointingTaskStartingLocations  20160 non-null  int64
 19  Trials                         20160 non-null  int64
 20  TrialNumber                    20160 non-null  int64
 21  StartPointID.1                 20160 non-null  int64
 22  ID_for_StartingPosition        20160 non-null  int64
 23  ImageIndexNumber               20160 non-null  int64
 24  ImageName                      20160 non-null  object
 25  TimeDelta                      20160 non-null  object
 26  RT                             20160 non-null  float64
 27  TimeOut                        20160 non-null  bool
 28  TimeStampBegin                 20160 non-null  object
 29  TimeStampEnd                   20160 non-null  object
 30  Angle                          20160 non-null  float64
 31  Unnamed: 0_keep                20160 non-null  int64
 32  BuildingCenterWorld.x          20160 non-null  float64
 33  BuildingCenterWorld.z          20160 non-null  float64
 34  Name                           20160 non-null  object
 35  BuildingName                   20160 non-null  object
 36  PointingTargetBuildingId       20160 non-null  int64
 37  AgentID                        20160 non-null  int64
 38  PointingTargetCondition        20160 non-null  object
 39  Context                        20160 non-null  bool
 40  Agent                          20160 non-null  bool
dtypes: bool(5), float64(14), int64(13), object(9)
memory usage: 5.8+ MB

In [7]:
CoordinatesIntegrated.groupby(['SubjectID', 'TrialNumber']).count()

                       Unnamed: 0_drop  ParticipantPosition_x  \
SubjectID TrialNumber
365       1                          2                      2
          2                          2                      2
          3                          2                      2
          4                          2                      2
          5                          2                      2
...                                ...                    ...
9601      332                        2                      2
          333                        2                      2
          334                        2                      2
          335                        2                      2
          336                        2                      2

                       ParticipantPosition_z  PointerPosition_x  \
SubjectID TrialNumber
365       1                                2                  2
          2                                2                  2
          3                                2                  2
          4                                2                  2
          5                                2                  2
...                                      ...                ...
9601      332                              2                  2
          333                              2                  2
          334                              2                  2
          335                              2                  2
          336                              2                  2

                       PointerPosition_z  PointerDirection_x  \
SubjectID TrialNumber
365       1                            2                   2
          2                            2                   2
          3                            2                   2
          4                            2                   2
          5                            2                   2
...                                  ...                 ...
9601      332                          2                   2
          333                          2                   2
          334                          2                   2
          335                          2                   2
          336                          2                   2

                       PointerDirection_z  PointerDirection_y  \
SubjectID TrialNumber
365       1                             2                   2
          2                             2                   2
          3                             2                   2
          4                             2                   2
          5                             2                   2
...                                   ...                 ...
9601      332                           2                   2
          333                           2                   2
          334                           2                   2
          335                           2                   2
          336                           2                   2

                       TargetBuildingPosition_x  TargetBuildingPosition_z  \
SubjectID TrialNumber
365       1                                   2                         2
          2                                   2                         2
          3                                   2                         2
          4                                   2                         2
          5                                   2                         2
...                                         ...                       ...
9601      332                                 2                         2
          333                                 2                         2
          334                                 2                         2
          335                                 2                         2
          336                                 2                         2

                       ...  Unnamed: 0_keep  BuildingCenterWorld.x  \
SubjectID TrialNumber  ...
365       1            ...                2                      2
          2            ...                2                      2
          3            ...                2                      2
          4            ...                2                      2
          5            ...                2                      2
...                    ...              ...                    ...
9601      332          ...                2                      2
          333          ...                2                      2
          334          ...                2                      2
          335          ...                2                      2
          336          ...                2                      2

                       BuildingCenterWorld.z  Name  BuildingName  \
SubjectID TrialNumber
365       1                                2     2             2
          2                                2     2             2
          3                                2     2             2
          4                                2     2             2
          5                                2     2             2
...                                      ...   ...           ...
9601      332                              2     2             2
          333                              2     2             2
          334                              2     2             2
          335                              2     2             2
          336                              2     2             2

                       PointingTargetBuildingId  AgentID  \
SubjectID TrialNumber
365       1                                   2        2
          2                                   2        2
          3                                   2        2
          4                                   2        2
          5                                   2        2
...                                         ...      ...
9601      332                                 2        2
          333                                 2        2
          334                                 2        2
          335                                 2        2
          336                                 2        2

                       PointingTargetCondition  Context  Agent
SubjectID TrialNumber
365       1                                  2        2      2
          2                                  2        2      2
          3                                  2        2      2
          4                                  2        2      2
          5                                  2        2      2
...                                        ...      ...    ...
9601      332                                2        2      2
          333                                2        2      2
          334                                2        2      2
          335                                2        2      2
          336                                2        2      2

[10080 rows x 39 columns]

In [8]:
CoordinatesIntegrated.rename(columns={"BuildingCenterWorld.z": "BuildingCenterWorld_z", "BuildingCenterWorld.x": "BuildingCenterWorld_x"}, inplace=True)

In [9]:
CoordinatesIntegrated = CoordinatesIntegrated[['SubjectID',
                                               'ParticipantPosition_x', 'ParticipantPosition_z',
                                               'PointerPosition_x','PointerPosition_z',
                                               'PointerDirection_x', 'PointerDirection_z',
                                               'BuildingCenterWorld_z', 'BuildingCenterWorld_x', 'DistanceToParticipant',
                                               'PointingTaskStartingLocations','AgentID', 'Name',
                                               'StartPointID','PointingTargetCondition', 'Context', 'Agent', 'avatarID','AvatarPresence', 'AvatarPresenceCategory', 'meaningful','meaningfulBuilding',
                                               'Trials', 'TrialNumber', 'StartPointID' ,'ID_for_StartingPosition','ImageName',
                                               'TimeDelta','RT', 'TimeOut', 'TimeStampBegin', 'TimeStampEnd']]

In [10]:
CoordinatesIntegrated.drop_duplicates(subset=['SubjectID', 'TrialNumber'], inplace=True)
CoordinatesIntegrated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10080 entries, 0 to 20158
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   SubjectID                      10080 non-null  int64
 1   ParticipantPosition_x          10080 non-null  float64
 2   ParticipantPosition_z          10080 non-null  float64
 3   PointerPosition_x              10080 non-null  float64
 4   PointerPosition_z              10080 non-null  float64
 5   PointerDirection_x             10080 non-null  float64
 6   PointerDirection_z             10080 non-null  float64
 7   BuildingCenterWorld_z          10080 non-null  float64
 8   BuildingCenterWorld_x          10080 non-null  float64
 9   DistanceToParticipant          10080 non-null  float64
 10  PointingTaskStartingLocations  10080 non-null  int64
 11  AgentID                        10080 non-null  int64
 12  Name                           10080 non-null  object
 13  StartPointID                   10080 non-null  int64
 14  PointingTargetCondition        10080 non-null  object
 15  Context                        10080 non-null  bool
 16  Agent                          10080 non-null  bool
 17  avatarID                       10080 non-null  int64
 18  AvatarPresence                 10080 non-null  bool
 19  AvatarPresenceCategory         10080 non-null  object
 20  meaningful                     10080 non-null  bool
 21  meaningfulBuilding             10080 non-null  object
 22  Trials                         10080 non-null  int64
 23  TrialNumber                    10080 non-null  int64
 24  StartPointID                   10080 non-null  int64
 25  ID_for_StartingPosition        10080 non-null  int64
 26  ImageName                      10080 non-null  object
 27  TimeDelta                      10080 non-null  object
 28  RT                             10080 non-null  float64
 29  TimeOut                        10080 non-null  bool
 30  TimeStampBegin                 10080 non-null  object
 31  TimeStampEnd                   10080 non-null  object
dtypes: bool(5), float64(10), int64(9), object(8)
memory usage: 2.2+ MB

In [11]:
CoordinatesIntegrated[['AvatarPresence', 'AvatarPresenceCategory', 'ImageName']]

       AvatarPresence AvatarPresenceCategory ImageName
0               False                Present     46_Sa
2                True                Omitted   46_SaNo
4               False                Present     46_Sa
6                True                Omitted   46_SaNo
8                True                Omitted   46_SaNo
...               ...                    ...       ...
20150            True                Omitted   53_SaNo
20152           False                Present     53_Sa
20154            True                Omitted   53_SaNo
20156           False                Present     53_Sa
20158           False                Present     53_Sa

[10080 rows x 3 columns]

In [12]:
# Added cell to set Working Directory to your location
os.chdir('//Volumes/TwoTeras/0_Experiment_1/Pointing_Task/Results/')
os.getcwd()

'/Volumes/TwoTeras/0_Experiment_1/Pointing_Task/Results'

In [13]:
CoordinatesIntegrated[['ImageName', 'avatarID']]

      ImageName  avatarID
0         46_Sa        46
2       46_SaNo        46
4         46_Sa        46
6       46_SaNo        46
8       46_SaNo        46
...         ...       ...
20150   53_SaNo        53
20152     53_Sa        53
20154   53_SaNo        53
20156     53_Sa        53
20158     53_Sa        53

[10080 rows x 2 columns]

In [14]:
CoordinatesIntegrated.to_csv('PointingTask_Integrated_exp1.csv')