# Joining experiment one and two

In [1]:
import pandas as pd 
import numpy as np

In [2]:
Exp_1 = pd.read_csv("//Volumes/SSD/Experiments_1_2/humanA_Behavioural.csv")
Exp_2 = pd.read_csv("/Volumes/SSD/Experiments_1_2/humanA_Behavioural_Building_withoutSuf.csv")

In [3]:
Exp_1.head()

,Unnamed: 0,ID,Alter,Global,Overview,Cardinal,AffiliativeQ_average,item3,ContextQ_average,remember_action_likert,...,DistanceToParticipant,PointingTaskStartingLocations,TrialNumber,StartPointID,ID_for_StartingPosition,avatarID,AvatarPresenceCategory,Context,meaningfulBuilding,ImageName
0,0,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,197.768723,21.0,1.0,1.0,1.0,46.0,Present,False,Not meaningful,46_Sa
1,1,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,213.475525,16.0,78.0,7.0,6.0,46.0,Omitted,False,Not meaningful,46_SaNo
2,2,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,111.623512,13.0,88.0,8.0,4.0,46.0,Present,False,Not meaningful,46_Sa
3,3,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,111.623512,13.0,95.0,8.0,11.0,46.0,Omitted,False,Not meaningful,46_SaNo
4,4,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,232.765823,8.0,131.0,11.0,11.0,46.0,Omitted,False,Not meaningful,46_SaNo

In [4]:
Exp_1["Experiment"] = 1
Exp_2["Experiment"] = 2

In [18]:
Exp_2.head(30)

,Unnamed: 0,ID,Alter,Global,Overview,Cardinal,AffiliativeQ_average,item3,ContextQ_average,remember_action_likert,...,PointingTaskStartingLocations,TrialNumber,StartPointID,ID_for_StartingPosition,avatarID,AvatarPresenceCategory,Context,meaningfulBuilding,ImageName,Experiment
0,0,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,20.0,153.0,20.0,1.0,33.0,Present,True,meaningful,33_CmA_20,2
1,1,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,22.0,54.0,7.0,6.0,43.0,Present,False,Not meaningful,43_Sa_55,2
2,2,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,14.0,81.0,11.0,1.0,43.0,Present,False,Not meaningful,43_Sa_55,2
3,3,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,14.0,84.0,11.0,4.0,43.0,Omitted,False,Not meaningful,43_SaNo_55,2
4,4,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,15.0,89.0,12.0,1.0,43.0,Present,False,Not meaningful,43_Sa_55,2
5,5,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,0.0,98.0,13.0,2.0,43.0,Present,False,Not meaningful,43_Sa_55,2
6,6,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,2.0,112.0,14.0,8.0,43.0,Omitted,False,Not meaningful,43_SaNo_55,2
7,7,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,4.0,78.0,10.0,6.0,44.0,Present,False,Not meaningful,44_Sa_18,2
8,8,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,12.0,44.0,6.0,4.0,55.0,Omitted,False,Not meaningful,55_SaNo_07,2
9,9,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,1.0,58.0,8.0,2.0,55.0,Omitted,False,Not meaningful,55_SaNo_07,2
10,10,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,1.0,64.0,8.0,8.0,55.0,Omitted,False,Not meaningful,55_SaNo_07,2
11,11,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,5.0,113.0,15.0,1.0,55.0,Omitted,False,Not meaningful,55_SaNo_07,2
12,12,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,7.0,151.0,19.0,7.0,55.0,Present,False,Not meaningful,55_Sa_07,2
13,13,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,6.0,66.0,9.0,2.0,37.0,Omitted,True,meaningful,37_CmANo_08,2
14,14,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,27.0,134.0,17.0,6.0,37.0,Omitted,True,meaningful,37_CmANo_08,2
15,15,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,7.0,146.0,19.0,2.0,37.0,Omitted,True,meaningful,37_CmANo_08,2
16,16,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,24.0,184.0,23.0,8.0,37.0,Omitted,True,meaningful,37_CmANo_08,2
17,17,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,25.0,211.0,27.0,3.0,37.0,Omitted,True,meaningful,37_CmANo_08,2
18,18,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,9.0,222.0,28.0,6.0,37.0,Present,True,meaningful,37_CmA_08,2
19,19,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,2.0,107.0,14.0,3.0,16.0,Omitted,False,Not meaningful,16_SaNoAct_36,2
20,20,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,7.0,149.0,19.0,5.0,16.0,Omitted,False,Not meaningful,16_SaNoAct_36,2
21,21,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,20.0,156.0,20.0,4.0,16.0,Omitted,False,Not meaningful,16_SaNoAct_36,2
22,22,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,6.0,67.0,9.0,3.0,49.0,Omitted,False,Not meaningful,49_SaNo_19,2
23,23,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,21.0,141.0,18.0,5.0,49.0,Present,False,Not meaningful,49_Sa_19,2
24,24,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,20.0,154.0,20.0,2.0,49.0,Present,False,Not meaningful,49_Sa_19,2
25,25,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,17.0,162.0,21.0,2.0,49.0,Present,False,Not meaningful,49_Sa_19,2
26,26,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,6.0,70.0,9.0,6.0,50.0,Omitted,False,Not meaningful,50_SaNo_15,2
27,27,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,14.0,83.0,11.0,3.0,50.0,Present,False,Not meaningful,50_Sa_15,2
28,28,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,14.0,87.0,11.0,7.0,50.0,Omitted,False,Not meaningful,50_SaNo_15,2
29,29,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,8.0,173.0,22.0,5.0,50.0,Omitted,False,Not meaningful,50_SaNo_15,2

In [6]:
Exp_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4259 entries, 0 to 4258
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     4259 non-null   int64
 1   ID                             4259 non-null   int64
 2   Alter                          4258 non-null   float64
 3   Global                         4258 non-null   float64
 4   Overview                       4258 non-null   float64
 5   Cardinal                       4258 non-null   float64
 6   AffiliativeQ_average           3808 non-null   float64
 7   item3                          3808 non-null   float64
 8   ContextQ_average               3808 non-null   float64
 9   remember_action_likert         4029 non-null   float64
 10  remember_standing_likert       4029 non-null   float64
 11  attractive_action_likert       4029 non-null   float64
 12  attractive_standing_likert     4029 non-null   float64
 13  realistic_action_likert        4029 non-null   float64
 14  realistic_standing_likert      4029 non-null   float64
 15  AbsolutError                   4251 non-null   float64
 16  SignedAngle-+180               4251 non-null   float64
 17  IQR                            4251 non-null   float64
 18  RT                             4251 non-null   float64
 19  DistanceToParticipant          4251 non-null   float64
 20  PointingTaskStartingLocations  4251 non-null   float64
 21  TrialNumber                    4251 non-null   float64
 22  StartPointID                   4251 non-null   float64
 23  ID_for_StartingPosition        4251 non-null   float64
 24  avatarID                       4251 non-null   float64
 25  AvatarPresenceCategory         4251 non-null   object
 26  Context                        4251 non-null   object
 27  BuildingCategory               4251 non-null   object
 28  ImageName                      4251 non-null   object
 29  Experiment                     4259 non-null   int64
dtypes: float64(23), int64(3), object(4)
memory usage: 998.3+ KB

In [7]:
Exp_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10049 entries, 0 to 10048
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10049 non-null  int64
 1   ID                             10049 non-null  float64
 2   Alter                          9718 non-null   float64
 3   Global                         9718 non-null   float64
 4   Overview                       9718 non-null   float64
 5   Cardinal                       9718 non-null   float64
 6   AffiliativeQ_average           9382 non-null   float64
 7   item3                          9382 non-null   float64
 8   ContextQ_average               9382 non-null   float64
 9   remember_action_likert         9713 non-null   float64
 10  remember_standing_likert       9713 non-null   float64
 11  attractive_action_likert       9713 non-null   float64
 12  attractive_standing_likert     9713 non-null   float64
 13  realistic_action_likert        9713 non-null   float64
 14  realistic_standing_likert      9713 non-null   float64
 15  AbsolutError                   10048 non-null  float64
 16  SignedAngle-+180               10048 non-null  float64
 17  IQR                            10048 non-null  float64
 18  RT                             10048 non-null  float64
 19  DistanceToParticipant          10048 non-null  float64
 20  PointingTaskStartingLocations  10048 non-null  float64
 21  TrialNumber                    10048 non-null  float64
 22  StartPointID                   10048 non-null  float64
 23  ID_for_StartingPosition        10048 non-null  float64
 24  avatarID                       10048 non-null  float64
 25  AvatarPresenceCategory         10048 non-null  object
 26  Context                        10048 non-null  object
 27  meaningfulBuilding             10048 non-null  object
 28  ImageName                      10048 non-null  object
 29  Experiment                     10049 non-null  int64
dtypes: float64(24), int64(2), object(4)
memory usage: 2.3+ MB

In [8]:
Exp_2.rename(columns={"BuildingCategory": "meaningfulBuilding"}, inplace=True)

In [9]:
result = pd.concat([Exp_1, Exp_2], axis=0)

In [10]:
result.tail()

,Unnamed: 0,ID,Alter,Global,Overview,Cardinal,AffiliativeQ_average,item3,ContextQ_average,remember_action_likert,...,PointingTaskStartingLocations,TrialNumber,StartPointID,ID_for_StartingPosition,avatarID,AvatarPresenceCategory,Context,meaningfulBuilding,ImageName,Experiment
4254,4254,1268.0,22.0,4.9,4.571429,1.0,3.4,3.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4255,4255,7823.0,22.0,4.7,3.000000,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4256,4256,4875.0,26.0,4.5,3.833333,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4257,4257,1574.0,23.0,5.8,2.857143,3.0,4.2,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4258,4258,4508.0,NaN,NaN,NaN,NaN,4.8,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [11]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14308 entries, 0 to 4258
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     14308 non-null  int64
 1   ID                             14308 non-null  float64
 2   Alter                          13976 non-null  float64
 3   Global                         13976 non-null  float64
 4   Overview                       13976 non-null  float64
 5   Cardinal                       13976 non-null  float64
 6   AffiliativeQ_average           13190 non-null  float64
 7   item3                          13190 non-null  float64
 8   ContextQ_average               13190 non-null  float64
 9   remember_action_likert         13742 non-null  float64
 10  remember_standing_likert       13742 non-null  float64
 11  attractive_action_likert       13742 non-null  float64
 12  attractive_standing_likert     13742 non-null  float64
 13  realistic_action_likert        13742 non-null  float64
 14  realistic_standing_likert      13742 non-null  float64
 15  AbsolutError                   14299 non-null  float64
 16  SignedAngle-+180               14299 non-null  float64
 17  IQR                            14299 non-null  float64
 18  RT                             14299 non-null  float64
 19  DistanceToParticipant          14299 non-null  float64
 20  PointingTaskStartingLocations  14299 non-null  float64
 21  TrialNumber                    14299 non-null  float64
 22  StartPointID                   14299 non-null  float64
 23  ID_for_StartingPosition        14299 non-null  float64
 24  avatarID                       14299 non-null  float64
 25  AvatarPresenceCategory         14299 non-null  object
 26  Context                        14299 non-null  object
 27  meaningfulBuilding             14299 non-null  object
 28  ImageName                      14299 non-null  object
 29  Experiment                     14308 non-null  int64
dtypes: float64(24), int64(2), object(4)
memory usage: 3.4+ MB

In [12]:
result

,Unnamed: 0,ID,Alter,Global,Overview,Cardinal,AffiliativeQ_average,item3,ContextQ_average,remember_action_likert,...,PointingTaskStartingLocations,TrialNumber,StartPointID,ID_for_StartingPosition,avatarID,AvatarPresenceCategory,Context,meaningfulBuilding,ImageName,Experiment
0,0,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,21.0,1.0,1.0,1.0,46.0,Present,False,Not meaningful,46_Sa,1
1,1,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,16.0,78.0,7.0,6.0,46.0,Omitted,False,Not meaningful,46_SaNo,1
2,2,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,13.0,88.0,8.0,4.0,46.0,Present,False,Not meaningful,46_Sa,1
3,3,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,13.0,95.0,8.0,11.0,46.0,Omitted,False,Not meaningful,46_SaNo,1
4,4,365.0,37.0,5.6,6.285714,2.5,5.2,2.0,3.5,2.714286,...,8.0,131.0,11.0,11.0,46.0,Omitted,False,Not meaningful,46_SaNo,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4254,4254,1268.0,22.0,4.9,4.571429,1.0,3.4,3.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4255,4255,7823.0,22.0,4.7,3.000000,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4256,4256,4875.0,26.0,4.5,3.833333,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4257,4257,1574.0,23.0,5.8,2.857143,3.0,4.2,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4258,4258,4508.0,NaN,NaN,NaN,NaN,4.8,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [13]:
result.tail()

,Unnamed: 0,ID,Alter,Global,Overview,Cardinal,AffiliativeQ_average,item3,ContextQ_average,remember_action_likert,...,PointingTaskStartingLocations,TrialNumber,StartPointID,ID_for_StartingPosition,avatarID,AvatarPresenceCategory,Context,meaningfulBuilding,ImageName,Experiment
4254,4254,1268.0,22.0,4.9,4.571429,1.0,3.4,3.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4255,4255,7823.0,22.0,4.7,3.000000,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4256,4256,4875.0,26.0,4.5,3.833333,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4257,4257,1574.0,23.0,5.8,2.857143,3.0,4.2,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4258,4258,4508.0,NaN,NaN,NaN,NaN,4.8,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [14]:
result["Agent_Action_level"] = np.where(np.isnan(result["avatarID"]), np.nan, np.where(result["avatarID"] > 28, "Passive", "Active"))

In [15]:
result[["avatarID","Agent_Action_level"]].head(50)

    avatarID Agent_Action_level
0       46.0            Passive
1       46.0            Passive
2       46.0            Passive
3       46.0            Passive
4       46.0            Passive
5       46.0            Passive
6       46.0            Passive
7       46.0            Passive
8       46.0            Passive
9       46.0            Passive
10      45.0            Passive
11      45.0            Passive
12      45.0            Passive
13      45.0            Passive
14      45.0            Passive
15      13.0             Active
16      13.0             Active
17      13.0             Active
18      13.0             Active
19      13.0             Active
20      13.0             Active
21      41.0            Passive
22      41.0            Passive
23      41.0            Passive
24      41.0            Passive
25      41.0            Passive
26      41.0            Passive
27      36.0            Passive
28      36.0            Passive
29      36.0            Passive
30      36.0            Passive
31      33.0            Passive
32      33.0            Passive
33      33.0            Passive
34      33.0            Passive
35      33.0            Passive
36      33.0            Passive
37      22.0             Active
38      22.0             Active
39      22.0             Active
40      22.0             Active
41      22.0             Active
42      22.0             Active
43      22.0             Active
44      22.0             Active
45      22.0             Active
46       2.0             Active
47       2.0             Active
48       2.0             Active
49       2.0             Active

In [23]:
Buildings_tags = pd.read_csv("/Volumes/SSD/Experiments_1_2/humanA_Behavioural_Building.csv")
Buildings_tags.columns

Index(['Unnamed: 0', 'ID', 'Alter ', 'Global', 'Overview', 'Cardinal',
       'AffiliativeQ_average', 'item3', 'ContextQ_average',
       'remember_action_likert', 'remember_standing_likert',
       'attractive_action_likert', 'attractive_standing_likert',
       'realistic_action_likert', 'realistic_standing_likert',
       'AbsolutError_Building', 'SignedAngle-+180_Building', 'IQR_Building',
       'RT_Building', 'DistanceToParticipant_Building',
       'PointingTaskStartingLocations_Building', 'TrialNumber_Building',
       'StartPointID_Building', 'ID_for_StartingPosition_Building',
       'avatarID_Building', 'AvatarPresenceCategory_Building',
       'Context_Building', 'BuildingCategory_Building', 'ImageName_Building'],
      dtype='object')

In [21]:
Buildings_tags.head()

,Unnamed: 0,ID,Alter,Global,Overview,Cardinal,AffiliativeQ_average,item3,ContextQ_average,remember_action_likert,...,DistanceToParticipant_Building,PointingTaskStartingLocations_Building,TrialNumber_Building,StartPointID_Building,ID_for_StartingPosition_Building,avatarID_Building,AvatarPresenceCategory_Building,Context_Building,BuildingCategory_Building,ImageName_Building
0,0,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,330.638397,20.0,153.0,20.0,1.0,33.0,Present,True,Public,33_CmA_20
1,1,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,263.351929,22.0,54.0,7.0,6.0,43.0,Present,False,Residential,43_Sa_55
2,2,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,327.918518,14.0,81.0,11.0,1.0,43.0,Present,False,Residential,43_Sa_55
3,3,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,327.918518,14.0,84.0,11.0,4.0,43.0,Omitted,False,Residential,43_SaNo_55
4,4,8629,23.0,4.3,5.714286,2.0,5.8,2.0,4.5,3.714286,...,274.974915,15.0,89.0,12.0,1.0,43.0,Present,False,Residential,43_Sa_55

In [25]:
Buildings_tags["Agent_Action_level"] = np.where(np.isnan(Buildings_tags["avatarID_Building"]), np.nan, np.where(Buildings_tags["avatarID_Building"] > 28, "Passive", "Active"))

In [26]:
Buildings_tags.to_csv("/Volumes/SSD/Experiments_1_2/humanA_Behavioural_Building.csv")

In [16]:
result.to_csv("/Volumes/SSD/Experiments_1_2/Experiments.csv")

In [8]:
experiment_1 = pd.read_csv("/Volumes/TwoTeras/0_Experiment_1/Eye_Tracking/Pre_processed/Data_Sets/BehavioralData_Fixations_Wide.csv")
experiment_1.rename({"meaningfulBuilding":"BuildingCategory"}, axis=1, inplace=True)
experiment_2 = pd.read_csv("/Volumes/TwoTeras/1_Experiment_2/Eye_Tracking/Pre_processed/Data_Sets/BehavioralData_Fixations_Wide.csv")

In [5]:
experiment_2.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'SubjectID', 'AbsolutError',
       'SignedAngle-+180', 'IQR', 'RT', 'DistanceToParticipant',
       'PointingTaskStartingLocations', 'TrialNumber', 'StartPointID',
       'ID_for_StartingPosition', 'avatar_ID', 'AvatarPresenceCategory',
       'Context', 'BuildingCategory', 'ImageName',
       'Dwelling_Time_Building_Gaze', 'Fixation_Count_Building_Gaze',
       'Dwelling_Time_Agent_Gaze', 'Fixation_Count_Agent_Gaze',
       'Agent_Category'],
      dtype='object')

In [6]:
experiment_1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'SubjectID', 'AbsolutError',
       'SignedAngle-+180', 'IQR', 'RT', 'DistanceToParticipant',
       'PointingTaskStartingLocations', 'TrialNumber', 'StartPointID',
       'ID_for_StartingPosition', 'avatar_ID', 'AvatarPresenceCategory',
       'Context', 'meaningfulBuilding', 'ImageName',
       'Dwelling_Time_Building_Gaze', 'Fixation_Count_Building_Gaze',
       'Dwelling_Time_Agent_Gaze', 'Fixation_Count_Agent_Gaze',
       'Agent_Action_level', 'Agent_Category'],
      dtype='object')

In [9]:
frames = [experiment_1, experiment_2]
result = pd.concat(frames)
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16314 entries, 0 to 6265
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     16314 non-null  int64
 1   Unnamed: 0.1                   16314 non-null  int64
 2   SubjectID                      16314 non-null  int64
 3   AbsolutError                   16314 non-null  float64
 4   SignedAngle-+180               16314 non-null  float64
 5   IQR                            16314 non-null  float64
 6   RT                             16314 non-null  float64
 7   DistanceToParticipant          16314 non-null  float64
 8   PointingTaskStartingLocations  16314 non-null  int64
 9   TrialNumber                    16314 non-null  int64
 10  StartPointID                   16314 non-null  int64
 11  ID_for_StartingPosition        16314 non-null  int64
 12  avatar_ID                      16314 non-null  int64
 13  AvatarPresenceCategory         16314 non-null  object
 14  Context                        16314 non-null  bool
 15  BuildingCategory               16314 non-null  object
 16  ImageName                      16314 non-null  object
 17  Dwelling_Time_Building_Gaze    14084 non-null  float64
 18  Fixation_Count_Building_Gaze   14084 non-null  float64
 19  Dwelling_Time_Agent_Gaze       14084 non-null  float64
 20  Fixation_Count_Agent_Gaze      14084 non-null  float64
 21  Agent_Action_level             10048 non-null  object
 22  Agent_Category                 16314 non-null  object
dtypes: bool(1), float64(9), int64(8), object(5)
memory usage: 2.9+ MB